import '../app/globals.css'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Closed-Loop Experimentation with Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white text-black">{children}</body>
    </html>
  )
}
